### ISSUE TITLE
VOX Intercom Communications

### ISSUE THREAD

**Issue by Dabble1SC** [FPGSchiba/VNGD-SimpleRadioStandalone#11]
This is not a requirement for release. Please do not spend much time on this.

**Comment by FPGSchiba** [comment]
This should be working now on the branch: [vox-development](https://github.com/FPGSchiba/VNGD-SimpleRadioStandalone/tree/feature/vox-development).

**Comment by Dabble1SC** [comment]
Reconfigure GUI to include "VOX" button, and channel selector

**Comment by Dabble1SC** [comment]
Change "INTERCOM" to "VOX Channel"

**Comment by VNGDArchangel-93** [comment]
Tada 
![Screenshot 2023-10-03 221445](https://github.com/FPGSchiba/VNGD-SimpleRadioStandalone/assets/20305784/142ba706-5b28-447b-93ac-a03663fc5363)

**Comment by VNGDArchangel-93** [comment]
Have not pushed it, so it is still local to my PC, but I got it working as best I can tell, Adam helped me make sure the number part was actually changing intercom channel

**Comment by VNGDArchangel-93** [comment]
Have not got color changing on VOX button working as of yet, will work on that

**Comment by FPGSchiba** [comment]
Colors are now Working:

![image](https://github.com/FPGSchiba/VNGD-SimpleRadioStandalone/assets/59923683/1675f77f-ce89-4e3c-b13f-3ca2e569a4c6)
![image](https://github.com/FPGSchiba/VNGD-SimpleRadioStandalone/assets/59923683/7d19da60-7789-4851-b189-0ffb82b2ff80)

**Comment by FPGSchiba** [comment]
Also added Vox Toggle to the 10 Radio Panel.

**Comment by FPGSchiba** [comment]
Is this now implemented @Dabble1SC ?

**Comment by Dabble1SC** [comment]
Closed.
