### ISSUE TITLE
Add a switch to the bottom of each radio panel that determines VOX source

### ISSUE THREAD

**Issue by Dabble1SC** [FPGSchiba/VNGD-SimpleRadioStandalone#20]
Add a three way switch that determines VOX Source: "Radio 1, Intercom, OFF"

Depending on the selection, VOX defaults to the selection. So, with the VOX switch in any position besides OFF, it turns it on. With Radio 1 selected, VOX would be defaulted to transmit over radio 1. Likewise, with intercom selected, VOX would be defaulted over Intercom.

**Comment by FPGSchiba** [comment]
This was implemented last week by me and is now in release 1.2.0-alpha.
