### ISSUE TITLE
Flickering on 5-radio panel when selecting UP/DOWN arrows on intercom channel button

### ISSUE THREAD

**Issue by Dabble1SC** [FPGSchiba/VNGD-SimpleRadioStandalone#26]
BUG: 5 radio flickers when selecting UP/DOWN arrows on intercom channel buttons

**Comment by FPGSchiba** [comment]
@VNGDArchangel-93 Is this fixed?
I know you did something with this, right?

**Comment by Dabble1SC** [comment]
This should be fixed. I can’t double check whether or not the this was merged with the master branch though.
