### ISSUE TITLE
Radio Panel - 3 Horizontal Radio

### ISSUE THREAD

**Issue by Dabble1SC** [FPGSchiba/VNGD-SimpleRadioStandalone#3]

**Comment by FPGSchiba** [comment]
![image](https://github.com/FPGSchiba/VNGD-SimpleRadioStandalone/assets/59923683/b721404c-e7e5-41b9-a26a-895945b1130c)
This is how it looks

**Comment by Dabble1SC** [comment]
@FPGSchiba Slight visual update. Let's move the Vox Selection R1 and IC buttons up below Radio 2 and in the same line as panel transparency and Vox/Intercom.

You may need to use the 10 Radio panel variant if that's easier.

![image](https://github.com/FPGSchiba/VNGD-SimpleRadioStandalone/assets/119721976/e5f68888-9e74-4e06-a01d-a32cf651b738)

**Comment by Dabble1SC** [comment]
Something like this:

![image](https://github.com/FPGSchiba/VNGD-SimpleRadioStandalone/assets/119721976/0160b290-c43a-4b30-86db-596f20b8b7d4)

**Comment by FPGSchiba** [comment]
Nope. this won't do, because of the size.
May be in the Overlay reworks

**Comment by Dabble1SC** [comment]
Can we change the various "components" to be smaller? That way we can squeeze all of the info into a single line?

Note in the mockup:
- Intercom is shortened to "IC"
- Intercom Volume squeezed to be smaller
- Transparency Slider is squeezed

The goal here is to take up as little space as possible vertically.

**Comment by FPGSchiba** [comment]
No, thats why I am saying that you can only Clip it, so it looks ugly
