### ISSUE TITLE
If you are still transmitting using VOX, and you PTT on an additional radio, you double transmitt

### ISSUE THREAD

**Issue by Dabble1SC** [FPGSchiba/VNGD-SimpleRadioStandalone#54]
We need to make the PTT button or radio select button automatically STOP the VOX activation process.

When the PTT button is release, VOX can be reenabled.

**Comment by FPGSchiba** [comment]
Pull Request is now open, for a Fix.
This was only visually, the backend did not receive simultaneous transmissions
